<template>
  <v-list nav density="compact">
    <v-list-item
      prepend-icon="mdi-chart-areaspline"
      title="订单预测"
      value="prediction"
      to="/index/schedulingplanning"
    ></v-list-item>
    <v-list-item
      prepend-icon="mdi-robot-industrial"
      title="AGV调度"
      value="agv-dispatch"
      to="/index/schedulingplanning/agv-dispatch"
    ></v-list-item>
    <v-list-item
      prepend-icon="mdi-image-search"
      title="划痕检测"
      value="agv-dispatch"
      to="/index/schedulingplanning/scratch-detection"
    ></v-list-item>
  </v-list>
</template>
